# permissions for end users to view podsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: image-sync-controller
    app.kubernetes.io/managed-by: kustomize
  name: image-podsync-viewer-role
rules:
- apiGroups:
  - image.apps.rkgcloud.com
  resources:
  - podsyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - image.apps.rkgcloud.com
  resources:
  - podsyncs/status
  verbs:
  - get
