---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - image.apps.rkgcloud.com
  resources:
  - imagesyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - image.apps.rkgcloud.com
  resources:
  - imagesyncs/finalizers
  verbs:
  - update
- apiGroups:
  - image.apps.rkgcloud.com
  resources:
  - imagesyncs/status
  verbs:
  - get
  - patch
  - update
