apiVersion: image.apps.rkgcloud.com/v1alpha1
kind: PodSync
metadata:
  labels:
    app.kubernetes.io/name: image-sync-controller
    app.kubernetes.io/managed-by: kustomize
  name: podsync-sample
spec:
  # TODO(user): Add fields here
  containers:
    - imageURL: nginx:latest
