apiVersion: image.apps.rkgcloud.com/v1alpha1
kind: ImageSync
metadata:
  labels:
    app.kubernetes.io/name: image-sync-controller
    app.kubernetes.io/managed-by: kustomize
  name: imagesync-sample
spec:
  # TODO(user): Add fields here
