apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: controller.image.apps.rkgcloud.com.0.0.0
spec:
  refName: controller.image.apps.rkgcloud.com
  releasedAt: null
  template:
    spec:
      deploy:
        - kapp: {}
      fetch:
        - git: {}
      template:
        - ytt:
            paths:
              - dist
        - kbld: {}
  valuesSchema:
    openAPIv3: null
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: controller.image.apps.rkgcloud.com
spec:
  displayName: controller
  longDescription: controller.image.apps.rkgcloud.com
  shortDescription: controller.image.apps.rkgcloud.com

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: controller
spec:
  packageRef:
    refName: controller.image.apps.rkgcloud.com
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: controller-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
